import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faRetweet,
    faHeart,
    faSmile,
    faPlus,
    faMinus,
    faEllipsisH,
    faBell,
    faAddressBook,
    faReply,
    faReplyAll,
    faGlobe,
    faLock,
    faEnvelope,
    faCog,
    faSignOutAlt,
    faEye,
    faEyeSlash,
    faHome,
    faCoffee,
    faPaperPlane,
    faAngleDown,
    faUser,
    faList,
    faBookmark,
    faUserCircle,
} from "@fortawesome/free-solid-svg-icons";

export function registerIcons() {
    library.add(
        faRetweet,
        faHeart,
        faSmile,
        faPlus,
        faMinus,
        faEllipsisH,
        faBell,
        faAddressBook,
        faReply,
        faReplyAll,
        faGlobe,
        faLock,
        faEnvelope,
        faCog,
        faSignOutAlt,
        faEye,
        faEyeSlash,
        faHome,
        faCoffee,
        faPaperPlane,
        faAngleDown,
        faUser,
        faList,
        faBookmark,
        faUserCircle,
    );
}
